"""empty message

Revision ID: 212f5afbc3aa
Revises: b9a532d9d7f1
Create Date: 2025-03-21 03:10:22.217834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212f5afbc3aa'
down_revision = 'b9a532d9d7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
