"""empty message

Revision ID: 2b02a7f7ba66
Revises: de409b9b065b
Create Date: 2025-04-03 01:56:24.287520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b02a7f7ba66'
down_revision = 'de409b9b065b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###
