"""empty message

Revision ID: 4fcf692a241e
Revises: b9a532d9d7f1
Create Date: 2025-03-21 22:53:01.243630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fcf692a241e'
down_revision = 'b9a532d9d7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('id_company', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'company', ['id_company'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_company')
        batch_op.drop_column('details')

    # ### end Alembic commands ###
