"""empty message

Revision ID: 517b098ee5de
Revises: 2b02a7f7ba66
Create Date: 2025-04-03 01:59:44.143535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517b098ee5de'
down_revision = '2b02a7f7ba66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('birthdate',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('birthdate',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
